/* Generated by port/tools/gen_yakumono_layout.py from the
 * stage structs in src/melee/gr.  Do not edit; rerun the
 * generator when a stage's yakumono_param struct changes.
 *
 * Each stage declares its own struct for the `yakumono_param`
 * symbol every Gr*.dat carries, so the layout is chosen by the
 * stage's GrKind, never by the block's size: several stages
 * share an extent with incompatible fields, which is what
 * findings R03-R05 of docs/review-fa257ed.md removed. */

#ifndef MELEE_HOST_YAKUMONO_PARAM_H
#define MELEE_HOST_YAKUMONO_PARAM_H

#include <melee_host/types.h>

/* grcastle.c: struct grCastle_YakumonoParam */
struct melee_host_yakumono_castle {
    /* 0x000 */ mh_s16 x0;
    /* 0x002 */ mh_s16 x2;
    /* 0x004 */ mh_s16 x4;
    /* 0x006 */ mh_s16 x6;
    /* 0x008 */ mh_s16 x8;
    /* 0x00A */ mh_s16 xA;
    /* 0x00C */ mh_s16 xC;
    /* 0x00E */ mh_s16 xE;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_u8 pad_x1C[4];
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_s16 x40;
    /* 0x042 */ mh_s16 x42;
    /* 0x044 */ mh_s16 x44;
    /* 0x046 */ mh_u8 pad_x46[2];
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_s16 x54;
    /* 0x056 */ mh_u8 pad_x56[2];
    /* 0x058 */ mh_s16 x58;
    /* 0x05A */ mh_u8 pad_x5A[2];
    /* 0x05C */ mh_s16 entries_0_x0;
    /* 0x05E */ mh_u8 entries_0_pad_x2[2];
    /* 0x060 */ mh_f32 entries_0_x4;
    /* 0x064 */ mh_f32 entries_0_rot_x;
    /* 0x068 */ mh_f32 entries_0_rot_y;
    /* 0x06C */ mh_f32 entries_0_rot_z;
    /* 0x070 */ mh_s16 entries_1_x0;
    /* 0x072 */ mh_u8 entries_1_pad_x2[2];
    /* 0x074 */ mh_f32 entries_1_x4;
    /* 0x078 */ mh_f32 entries_1_rot_x;
    /* 0x07C */ mh_f32 entries_1_rot_y;
    /* 0x080 */ mh_f32 entries_1_rot_z;
    /* 0x084 */ mh_s16 entries_2_x0;
    /* 0x086 */ mh_u8 entries_2_pad_x2[2];
    /* 0x088 */ mh_f32 entries_2_x4;
    /* 0x08C */ mh_f32 entries_2_rot_x;
    /* 0x090 */ mh_f32 entries_2_rot_y;
    /* 0x094 */ mh_f32 entries_2_rot_z;
    /* 0x098 */ mh_s16 entries_3_x0;
    /* 0x09A */ mh_u8 entries_3_pad_x2[2];
    /* 0x09C */ mh_f32 entries_3_x4;
    /* 0x0A0 */ mh_f32 entries_3_rot_x;
    /* 0x0A4 */ mh_f32 entries_3_rot_y;
    /* 0x0A8 */ mh_f32 entries_3_rot_z;
    /* 0x0AC */ mh_s16 entries_4_x0;
    /* 0x0AE */ mh_u8 entries_4_pad_x2[2];
    /* 0x0B0 */ mh_f32 entries_4_x4;
    /* 0x0B4 */ mh_f32 entries_4_rot_x;
    /* 0x0B8 */ mh_f32 entries_4_rot_y;
    /* 0x0BC */ mh_f32 entries_4_rot_z;
    /* 0x0C0 */ mh_s16 entries_5_x0;
    /* 0x0C2 */ mh_u8 entries_5_pad_x2[2];
    /* 0x0C4 */ mh_f32 entries_5_x4;
    /* 0x0C8 */ mh_f32 entries_5_rot_x;
    /* 0x0CC */ mh_f32 entries_5_rot_y;
    /* 0x0D0 */ mh_f32 entries_5_rot_z;
    /* 0x0D4 */ mh_s16 entries_6_x0;
    /* 0x0D6 */ mh_u8 entries_6_pad_x2[2];
    /* 0x0D8 */ mh_f32 entries_6_x4;
    /* 0x0DC */ mh_f32 entries_6_rot_x;
    /* 0x0E0 */ mh_f32 entries_6_rot_y;
    /* 0x0E4 */ mh_f32 entries_6_rot_z;
    /* 0x0E8 */ mh_s16 entries_7_x0;
    /* 0x0EA */ mh_u8 entries_7_pad_x2[2];
    /* 0x0EC */ mh_f32 entries_7_x4;
    /* 0x0F0 */ mh_f32 entries_7_rot_x;
    /* 0x0F4 */ mh_f32 entries_7_rot_y;
    /* 0x0F8 */ mh_f32 entries_7_rot_z;
    /* 0x0FC */ mh_s16 entries_8_x0;
    /* 0x0FE */ mh_u8 entries_8_pad_x2[2];
    /* 0x100 */ mh_f32 entries_8_x4;
    /* 0x104 */ mh_f32 entries_8_rot_x;
    /* 0x108 */ mh_f32 entries_8_rot_y;
    /* 0x10C */ mh_f32 entries_8_rot_z;
    /* 0x110 */ mh_f32 x110;
    /* 0x114 */ void* x114;
    /* 0x118 */ mh_f32 x118;
    /* 0x11C */ mh_f32 x11C;
    /* 0x120 */ mh_f32 x120;
    /* 0x124 */ mh_f32 x124;
    /* 0x128 */ mh_u8 pad_x128[4];
    /* 0x12C */ mh_s16 x12C[4];
    /* 0x134 */ mh_f32 x134;
    /* 0x138 */ mh_f32 x138;
    /* 0x13C */ mh_f32 x13C;
    /* 0x140 */ mh_f32 x140;
};

/* grrcruise.c: struct grRCruise_YakumonoParam */
struct melee_host_yakumono_rcruise {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_s32 xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_s32 x14;
    /* 0x018 */ mh_s32 x18;
    /* 0x01C */ mh_s32 x1C;
    /* 0x020 */ mh_s32 x20;
    /* 0x024 */ mh_s32 x24;
    /* 0x028 */ mh_s32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_s32 x3C;
    /* 0x040 */ mh_s32 x40;
    /* 0x044 */ mh_s32 x44;
};

/* grkongo.c: struct grKongo_YakumonoParam */
struct melee_host_yakumono_kongo {
    /* 0x000 */ mh_f32 unk0;
    /* 0x004 */ mh_f32 unk4;
    /* 0x008 */ mh_f32 unk8;
    /* 0x00C */ mh_f32 unkC;
    /* 0x010 */ mh_f32 unk10;
    /* 0x014 */ mh_f32 unk14;
    /* 0x018 */ mh_f32 unk18;
    /* 0x01C */ mh_f32 unk1C;
    /* 0x020 */ mh_f32 unk20;
    /* 0x024 */ mh_f32 unk24;
    /* 0x028 */ mh_f32 unk28;
    /* 0x02C */ mh_f32 unk2C;
    /* 0x030 */ mh_f32 unk30;
    /* 0x034 */ mh_f32 unk34;
    /* 0x038 */ mh_f32 unk38;
    /* 0x03C */ mh_f32 unk3C;
    /* 0x040 */ mh_f32 unk40;
    /* 0x044 */ mh_s16 unk44;
    /* 0x046 */ mh_s16 unk46;
    /* 0x048 */ mh_s16 unk48;
    /* 0x04A */ mh_s16 unk4A;
    /* 0x04C */ mh_s16 unk4C;
    /* 0x04E */ mh_s16 unk4E;
    /* 0x050 */ mh_s16 unk50;
    /* 0x052 */ mh_s16 unk52;
    /* 0x054 */ mh_f32 unk54;
    /* 0x058 */ mh_f32 unk58;
    /* 0x05C */ mh_f32 unk5C;
    /* 0x060 */ mh_f32 unk60;
    /* 0x064 */ mh_s32 unk64;
    /* 0x068 */ mh_s32 unk68;
    /* 0x06C */ mh_f32 unk6C;
    /* 0x070 */ mh_f32 unk70;
    /* 0x074 */ mh_f32 unk74;
    /* 0x078 */ mh_f32 unk78;
    /* 0x07C */ mh_f32 unk7C;
    /* 0x080 */ mh_f32 unk80;
    /* 0x084 */ void* unk84;
    /* 0x088 */ mh_f32 unk88;
    /* 0x08C */ mh_f32 unk8C;
    /* 0x090 */ mh_f32 unk90;
    /* 0x094 */ mh_f32 unk94;
    /* 0x098 */ mh_f32 unk98;
    /* 0x09C */ mh_f32 unk9C;
    /* 0x0A0 */ mh_f32 unkA0;
    /* 0x0A4 */ mh_f32 unkA4;
    /* 0x0A8 */ mh_f32 unkA8;
    /* 0x0AC */ mh_f32 unkAC;
    /* 0x0B0 */ mh_f32 unkB0;
    /* 0x0B4 */ mh_f32 unkB4;
    /* 0x0B8 */ mh_f32 unkB8;
};

/* grgarden.c: struct grGarden_YakumonoParam */
struct melee_host_yakumono_garden {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_s32 x8;
    /* 0x00C */ mh_s32 xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_s32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
};

/* grzebes.c: grZe_YakumonoParam */
struct melee_host_yakumono_zebes {
    /* 0x000 */ mh_f32 x00;
    /* 0x004 */ mh_f32 x04;
    /* 0x008 */ mh_f32 x08;
    /* 0x00C */ mh_f32 x0C;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_u8 pad_14[28];
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_f32 x54;
    /* 0x058 */ mh_f32 x58;
    /* 0x05C */ mh_f32 x5C;
    /* 0x060 */ mh_f32 x60;
    /* 0x064 */ mh_f32 x64;
    /* 0x068 */ mh_f32 x68;
    /* 0x06C */ mh_f32 x6C;
    /* 0x070 */ mh_f32 x70;
    /* 0x074 */ mh_f32 x74;
    /* 0x078 */ mh_f32 x78;
    /* 0x07C */ mh_f32 x7C;
    /* 0x080 */ mh_f32 x80;
    /* 0x084 */ mh_f32 x84;
    /* 0x088 */ mh_f32 x88;
    /* 0x08C */ mh_f32 x8C;
    /* 0x090 */ mh_f32 x90;
    /* 0x094 */ mh_f32 x94;
    /* 0x098 */ mh_f32 x98;
    /* 0x09C */ mh_f32 x9C;
    /* 0x0A0 */ mh_s16 xA0_entries_0_x0_base;
    /* 0x0A2 */ mh_s16 xA0_entries_0_x2_delay_min;
    /* 0x0A4 */ mh_s16 xA0_entries_0_x4_delay_max;
    /* 0x0A6 */ mh_s16 xA0_entries_0_x6_level;
    /* 0x0A8 */ mh_s16 xA0_entries_1_x0_base;
    /* 0x0AA */ mh_s16 xA0_entries_1_x2_delay_min;
    /* 0x0AC */ mh_s16 xA0_entries_1_x4_delay_max;
    /* 0x0AE */ mh_s16 xA0_entries_1_x6_level;
    /* 0x0B0 */ mh_s16 xA0_entries_2_x0_base;
    /* 0x0B2 */ mh_s16 xA0_entries_2_x2_delay_min;
    /* 0x0B4 */ mh_s16 xA0_entries_2_x4_delay_max;
    /* 0x0B6 */ mh_s16 xA0_entries_2_x6_level;
    /* 0x0B8 */ mh_s16 xA0_entries_3_x0_base;
    /* 0x0BA */ mh_s16 xA0_entries_3_x2_delay_min;
    /* 0x0BC */ mh_s16 xA0_entries_3_x4_delay_max;
    /* 0x0BE */ mh_s16 xA0_entries_3_x6_level;
    /* 0x0C0 */ mh_s16 xA0_entries_4_x0_base;
    /* 0x0C2 */ mh_s16 xA0_entries_4_x2_delay_min;
    /* 0x0C4 */ mh_s16 xA0_entries_4_x4_delay_max;
    /* 0x0C6 */ mh_s16 xA0_entries_4_x6_level;
    /* 0x0C8 */ mh_s16 xA0_entries_5_x0_base;
    /* 0x0CA */ mh_s16 xA0_entries_5_x2_delay_min;
    /* 0x0CC */ mh_s16 xA0_entries_5_x4_delay_max;
    /* 0x0CE */ mh_s16 xA0_entries_5_x6_level;
    /* 0x0D0 */ mh_s16 xA0_entries_6_x0_base;
    /* 0x0D2 */ mh_s16 xA0_entries_6_x2_delay_min;
    /* 0x0D4 */ mh_s16 xA0_entries_6_x4_delay_max;
    /* 0x0D6 */ mh_s16 xA0_entries_6_x6_level;
    /* 0x0D8 */ mh_s16 xA0_entries_7_x0_base;
    /* 0x0DA */ mh_s16 xA0_entries_7_x2_delay_min;
    /* 0x0DC */ mh_s16 xA0_entries_7_x4_delay_max;
    /* 0x0DE */ mh_s16 xA0_entries_7_x6_level;
    /* 0x0E0 */ mh_s16 xA0_entries_8_x0_base;
    /* 0x0E2 */ mh_s16 xA0_entries_8_x2_delay_min;
    /* 0x0E4 */ mh_s16 xA0_entries_8_x4_delay_max;
    /* 0x0E6 */ mh_s16 xA0_entries_8_x6_level;
    /* 0x0E8 */ mh_s16 xA0_entries_9_x0_base;
    /* 0x0EA */ mh_s16 xA0_entries_9_x2_delay_min;
    /* 0x0EC */ mh_s16 xA0_entries_9_x4_delay_max;
    /* 0x0EE */ mh_s16 xA0_entries_9_x6_level;
    /* 0x0F0 */ mh_s16 xA0_entries_10_x0_base;
    /* 0x0F2 */ mh_s16 xA0_entries_10_x2_delay_min;
    /* 0x0F4 */ mh_s16 xA0_entries_10_x4_delay_max;
    /* 0x0F6 */ mh_s16 xA0_entries_10_x6_level;
    /* 0x0F8 */ mh_s16 xA0_entries_11_x0_base;
    /* 0x0FA */ mh_s16 xA0_entries_11_x2_delay_min;
    /* 0x0FC */ mh_s16 xA0_entries_11_x4_delay_max;
    /* 0x0FE */ mh_s16 xA0_entries_11_x6_level;
    /* 0x100 */ mh_s16 xA0_entries_12_x0_base;
    /* 0x102 */ mh_s16 xA0_entries_12_x2_delay_min;
    /* 0x104 */ mh_s16 xA0_entries_12_x4_delay_max;
    /* 0x106 */ mh_s16 xA0_entries_12_x6_level;
    /* 0x108 */ mh_s16 xA0_entries_13_x0_base;
    /* 0x10A */ mh_s16 xA0_entries_13_x2_delay_min;
    /* 0x10C */ mh_s16 xA0_entries_13_x4_delay_max;
    /* 0x10E */ mh_s16 xA0_entries_13_x6_level;
    /* 0x110 */ mh_s16 xA0_entries_14_x0_base;
    /* 0x112 */ mh_s16 xA0_entries_14_x2_delay_min;
    /* 0x114 */ mh_s16 xA0_entries_14_x4_delay_max;
    /* 0x116 */ mh_s16 xA0_entries_14_x6_level;
    /* 0x118 */ mh_s16 xA0_entries_15_x0_base;
    /* 0x11A */ mh_s16 xA0_entries_15_x2_delay_min;
    /* 0x11C */ mh_s16 xA0_entries_15_x4_delay_max;
    /* 0x11E */ mh_s16 xA0_entries_15_x6_level;
    /* 0x120 */ mh_s16 xA0_entries_16_x0_base;
    /* 0x122 */ mh_s16 xA0_entries_16_x2_delay_min;
    /* 0x124 */ mh_s16 xA0_entries_16_x4_delay_max;
    /* 0x126 */ mh_s16 xA0_entries_16_x6_level;
    /* 0x128 */ mh_s16 xA0_entries_17_x0_base;
    /* 0x12A */ mh_s16 xA0_entries_17_x2_delay_min;
    /* 0x12C */ mh_s16 xA0_entries_17_x4_delay_max;
    /* 0x12E */ mh_s16 xA0_entries_17_x6_level;
    /* 0x130 */ mh_s16 xA0_entries_18_x0_base;
    /* 0x132 */ mh_s16 xA0_entries_18_x2_delay_min;
    /* 0x134 */ mh_s16 xA0_entries_18_x4_delay_max;
    /* 0x136 */ mh_s16 xA0_entries_18_x6_level;
    /* 0x138 */ mh_s16 xA0_entries_19_x0_base;
    /* 0x13A */ mh_s16 xA0_entries_19_x2_delay_min;
    /* 0x13C */ mh_s16 xA0_entries_19_x4_delay_max;
    /* 0x13E */ mh_s16 xA0_entries_19_x6_level;
    /* 0x140 */ mh_s16 xA0_entries_20_x0_base;
    /* 0x142 */ mh_s16 xA0_entries_20_x2_delay_min;
    /* 0x144 */ mh_s16 xA0_entries_20_x4_delay_max;
    /* 0x146 */ mh_s16 xA0_entries_20_x6_level;
    /* 0x148 */ mh_s16 xA0_entries_21_x0_base;
    /* 0x14A */ mh_s16 xA0_entries_21_x2_delay_min;
    /* 0x14C */ mh_s16 xA0_entries_21_x4_delay_max;
    /* 0x14E */ mh_s16 xA0_entries_21_x6_level;
    /* 0x150 */ mh_s16 xA0_entries_22_x0_base;
    /* 0x152 */ mh_s16 xA0_entries_22_x2_delay_min;
    /* 0x154 */ mh_s16 xA0_entries_22_x4_delay_max;
    /* 0x156 */ mh_s16 xA0_entries_22_x6_level;
    /* 0x158 */ mh_s16 xA0_entries_23_x0_base;
    /* 0x15A */ mh_s16 xA0_entries_23_x2_delay_min;
    /* 0x15C */ mh_s16 xA0_entries_23_x4_delay_max;
    /* 0x15E */ mh_s16 xA0_entries_23_x6_level;
    /* 0x160 */ mh_s16 xA0_entries_24_x0_base;
    /* 0x162 */ mh_s16 xA0_entries_24_x2_delay_min;
    /* 0x164 */ mh_s16 xA0_entries_24_x4_delay_max;
    /* 0x166 */ mh_s16 xA0_entries_24_x6_level;
    /* 0x168 */ mh_s16 xA0_entries_25_x0_base;
    /* 0x16A */ mh_s16 xA0_entries_25_x2_delay_min;
    /* 0x16C */ mh_s16 xA0_entries_25_x4_delay_max;
    /* 0x16E */ mh_s16 xA0_entries_25_x6_level;
    /* 0x170 */ mh_s16 xA0_entries_26_x0_base;
    /* 0x172 */ mh_s16 xA0_entries_26_x2_delay_min;
    /* 0x174 */ mh_s16 xA0_entries_26_x4_delay_max;
    /* 0x176 */ mh_s16 xA0_entries_26_x6_level;
    /* 0x178 */ mh_s16 xA0_entries_27_x0_base;
    /* 0x17A */ mh_s16 xA0_entries_27_x2_delay_min;
    /* 0x17C */ mh_s16 xA0_entries_27_x4_delay_max;
    /* 0x17E */ mh_s16 xA0_entries_27_x6_level;
    /* 0x180 */ mh_s16 xA0_entries_28_x0_base;
    /* 0x182 */ mh_s16 xA0_entries_28_x2_delay_min;
    /* 0x184 */ mh_s16 xA0_entries_28_x4_delay_max;
    /* 0x186 */ mh_s16 xA0_entries_28_x6_level;
    /* 0x188 */ mh_s16 xA0_entries_29_x0_base;
    /* 0x18A */ mh_s16 xA0_entries_29_x2_delay_min;
    /* 0x18C */ mh_s16 xA0_entries_29_x4_delay_max;
    /* 0x18E */ mh_s16 xA0_entries_29_x6_level;
};

/* grkraid.c: struct grKraid_YakumonoParam */
struct melee_host_yakumono_kraid {
    /* 0x000 */ mh_u32 map_time_min;
    /* 0x004 */ mh_u32 map_time_max;
    /* 0x008 */ mh_s32 map_time_acl;
    /* 0x00C */ mh_f32 map_rot_spd_min;
    /* 0x010 */ mh_f32 map_rot_spd_max;
    /* 0x014 */ mh_u32 kraid_wait_time;
    /* 0x018 */ mh_u32 kraid_wait_time_add;
    /* 0x01C */ mh_f32 kraid_pos_x[6];
};

/* grstory.c: struct grStory_YakumonoParam */
struct melee_host_yakumono_story {
    /* 0x000 */ mh_f32 timer_min;
    /* 0x004 */ mh_f32 timer_rand;
    /* 0x008 */ mh_f32 spawnmany_rarity;
    /* 0x00C */ mh_f32 vpos[6];
};

/* grizumi.c: struct grIzumi_YakumonoParam */
struct melee_host_yakumono_izumi {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_s32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
};

/* grgreens.c: struct grGreens_YakumonoParam */
struct melee_host_yakumono_greens {
    /* 0x000 */ mh_s32 x0_blockTimerMin;
    /* 0x004 */ mh_s32 x4_blockTimerMax;
    /* 0x008 */ mh_s32 x8_blockBombChance;
    /* 0x00C */ mh_s32 xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_s32 x14;
    /* 0x018 */ mh_s32 x18;
    /* 0x01C */ mh_s32 x1C;
    /* 0x020 */ mh_s32 x20;
    /* 0x024 */ mh_s32 x24;
    /* 0x028 */ mh_s32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_s32 x34_windTimerMin;
    /* 0x038 */ mh_s32 x38_windTimerMax;
    /* 0x03C */ mh_f32 x3C_windSpeed;
    /* 0x040 */ mh_f32 x40_left;
    /* 0x044 */ mh_f32 x44_right;
    /* 0x048 */ mh_f32 x48_top;
    /* 0x04C */ mh_f32 x4C_bottom;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_f32 x54;
    /* 0x058 */ mh_f32 x58;
    /* 0x05C */ mh_s32 x5C;
    /* 0x060 */ mh_s32 x60;
    /* 0x064 */ mh_s32 x64;
    /* 0x068 */ mh_s32 x68;
    /* 0x06C */ mh_f32 x6C;
    /* 0x070 */ mh_f32 x70;
    /* 0x074 */ mh_f32 x74;
    /* 0x078 */ mh_f32 x78;
};

/* grcorneria.c: struct grCorneria_YakumonoParam */
struct melee_host_yakumono_corneria {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_u8 pad50[24];
    /* 0x068 */ mh_f32 x68;
    /* 0x06C */ mh_u8 pad6C[4];
    /* 0x070 */ mh_f32 x70;
    /* 0x074 */ mh_s32 x74;
    /* 0x078 */ mh_s32 x78;
    /* 0x07C */ mh_s32 x7C;
    /* 0x080 */ mh_s32 x80;
    /* 0x084 */ void* x84;
    /* 0x088 */ mh_f32 x88;
};

/* grvenom.c: struct grVenom_YakumonoParam */
struct melee_host_yakumono_venom {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_s8 x14[24];
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_s8 x30[4];
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ void* x38;
};

/* grpstadium.c: anon */
struct melee_host_yakumono_pstadium {
    /* 0x000 */ mh_s32 x0;
    /* 0x004 */ mh_s32 x4;
    /* 0x008 */ mh_s32 x8;
    /* 0x00C */ mh_s32 xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_s32 x14;
    /* 0x018 */ mh_s32 x18;
    /* 0x01C */ mh_u8 r;
    /* 0x01D */ mh_u8 g;
    /* 0x01E */ mh_u8 b;
    /* 0x020 */ mh_u32 x20;
    /* 0x024 */ mh_u32 x24;
    /* 0x028 */ mh_u32 x28;
    /* 0x02C */ mh_u32 x2C;
    /* 0x030 */ mh_u32 x30;
    /* 0x034 */ mh_u32 x34;
    /* 0x038 */ mh_u32 x38;
    /* 0x03C */ mh_u32 x3C;
    /* 0x040 */ mh_u32 x40;
    /* 0x044 */ mh_u32 x44;
    /* 0x048 */ mh_s16 x48;
    /* 0x04A */ mh_s16 x4A;
    /* 0x04C */ mh_s16 x4C;
    /* 0x04E */ mh_s16 x4E;
    /* 0x050 */ mh_s16 x50;
};

/* grmutecity.c: struct grMc_YakumonoParam */
struct melee_host_yakumono_mutecity {
    /* 0x000 */ void* x0;
    /* 0x004 */ void* x4;
    /* 0x008 */ void* x8;
    /* 0x00C */ void* xC;
    /* 0x010 */ mh_u8 pad10[28];
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
};

/* grbigblue.c: grBb_YakumonoParam */
struct melee_host_yakumono_bigblue {
    /* 0x000 */ mh_f32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_s32 x14;
    /* 0x018 */ mh_s32 x18;
    /* 0x01C */ mh_s32 x1C;
    /* 0x020 */ mh_s32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_f32 x54;
    /* 0x058 */ mh_f32 x58;
    /* 0x05C */ mh_f32 x5C;
    /* 0x060 */ mh_f32 x60;
    /* 0x064 */ mh_u8 pad64[4];
    /* 0x068 */ mh_f32 x68;
    /* 0x06C */ mh_f32 x6C;
    /* 0x070 */ mh_f32 x70;
    /* 0x074 */ mh_f32 x74;
    /* 0x078 */ mh_f32 x78;
    /* 0x07C */ mh_f32 x7C;
    /* 0x080 */ mh_f32 x80;
    /* 0x084 */ mh_f32 x84;
    /* 0x088 */ mh_s32 x88;
    /* 0x08C */ mh_s32 x8C;
    /* 0x090 */ mh_f32 x90;
    /* 0x094 */ mh_f32 x94;
    /* 0x098 */ mh_f32 x98;
    /* 0x09C */ mh_f32 x9C;
    /* 0x0A0 */ mh_f32 xA0;
    /* 0x0A4 */ mh_f32 xA4;
    /* 0x0A8 */ mh_f32 xA8;
    /* 0x0AC */ mh_f32 xAC;
    /* 0x0B0 */ mh_s32 xB0;
    /* 0x0B4 */ mh_s32 xB4;
    /* 0x0B8 */ mh_s32 xB8;
    /* 0x0BC */ mh_f32 xBC;
    /* 0x0C0 */ mh_f32 xC0;
    /* 0x0C4 */ mh_f32 xC4;
    /* 0x0C8 */ mh_f32 xC8;
    /* 0x0CC */ mh_f32 xCC;
    /* 0x0D0 */ mh_f32 xD0;
    /* 0x0D4 */ mh_f32 xD4;
    /* 0x0D8 */ mh_f32 xD8;
    /* 0x0DC */ mh_s32 xDC;
    /* 0x0E0 */ mh_s32 xE0;
    /* 0x0E4 */ mh_f32 xE4;
    /* 0x0E8 */ mh_f32 xE8;
    /* 0x0EC */ mh_f32 xEC;
    /* 0x0F0 */ mh_f32 xF0;
    /* 0x0F4 */ mh_f32 xF4;
    /* 0x0F8 */ mh_f32 xF8;
    /* 0x0FC */ mh_f32 xFC;
    /* 0x100 */ mh_f32 x100;
    /* 0x104 */ mh_f32 x104;
    /* 0x108 */ mh_f32 x108;
    /* 0x10C */ mh_s32 x10C;
    /* 0x110 */ mh_s32 x110;
    /* 0x114 */ mh_u8 pad114[8];
    /* 0x11C */ mh_s32 x11C;
    /* 0x120 */ mh_s32 x120;
    /* 0x124 */ mh_f32 x124;
    /* 0x128 */ mh_f32 x128;
    /* 0x12C */ mh_f32 x12C;
    /* 0x130 */ mh_f32 x130;
    /* 0x134 */ mh_f32 x134_translate_x;
    /* 0x138 */ mh_f32 x134_translate_y;
    /* 0x13C */ mh_f32 x134_translate_z;
    /* 0x140 */ mh_f32 x140_scale;
};

/* gronett.c: struct grOnett_StageParam */
struct melee_host_yakumono_onett {
    /* 0x000 */ mh_f32 awning_initial;
    /* 0x004 */ mh_f32 max_velocity;
    /* 0x008 */ mh_f32 vel_threshold;
    /* 0x00C */ mh_f32 pos_threshold;
    /* 0x010 */ mh_f32 damping;
    /* 0x014 */ mh_f32 spring_force;
    /* 0x018 */ mh_f32 spring_constant;
    /* 0x01C */ mh_f32 max_displacement;
    /* 0x020 */ mh_f32 awning_delta;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_f32 x34;
    /* 0x038 */ mh_f32 x38;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_f32 x54;
    /* 0x058 */ mh_f32 x58;
    /* 0x05C */ mh_f32 x5C;
    /* 0x060 */ mh_f32 x60;
    /* 0x064 */ mh_f32 x64;
};

/* grfourside.c: struct grFourside_YakumonoParam */
struct melee_host_yakumono_fourside {
    /* 0x000 */ mh_s32 heli_wait;
    /* 0x004 */ mh_s32 heli_wait_add;
    /* 0x008 */ mh_s32 heli_stay_time;
    /* 0x00C */ mh_s32 crane_wait;
    /* 0x010 */ mh_s32 crane_wait_add;
    /* 0x014 */ mh_s32 crane_iron_wait;
    /* 0x018 */ mh_s32 crane_iron_wait_add;
    /* 0x01C */ mh_f32 crane_iron_up_min;
    /* 0x020 */ mh_f32 crane_iron_up_max;
    /* 0x024 */ mh_f32 crane_iron_down_min;
    /* 0x028 */ mh_f32 crane_iron_down_max;
    /* 0x02C */ mh_f32 crane_iron_spd;
    /* 0x030 */ mh_f32 crane_iron_stop_acl;
    /* 0x034 */ mh_s32 ufo_wait;
    /* 0x038 */ mh_f32 ufo_cs_offs;
    /* 0x03C */ mh_s32 ufo_stay_time;
    /* 0x040 */ mh_s32 ufo_stay_time_add;
    /* 0x044 */ mh_u16 ufo_challenge;
    /* 0x046 */ mh_u16 x46;
    /* 0x048 */ mh_u16 x48;
};

/* gricemt.c: struct grIceMt_YakumonoParam */
struct melee_host_yakumono_icemt {
    /* 0x000 */ mh_s16 x0;
    /* 0x002 */ mh_s16 x2;
    /* 0x004 */ mh_s16 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
    /* 0x034 */ mh_s16 x34;
    /* 0x036 */ mh_s16 x36;
    /* 0x038 */ mh_s16 x38;
    /* 0x03A */ mh_u16 x3A;
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
    /* 0x050 */ mh_f32 x50;
    /* 0x054 */ mh_f32 x54;
    /* 0x058 */ mh_f32 x58;
    /* 0x05C */ mh_f32 x5C;
    /* 0x060 */ mh_f32 x60;
    /* 0x064 */ mh_f32 x64;
    /* 0x068 */ mh_f32 x68;
    /* 0x06C */ mh_f32 x6C;
    /* 0x070 */ mh_f32 x70;
    /* 0x074 */ mh_f32 x74;
    /* 0x078 */ mh_f32 x78;
    /* 0x07C */ mh_f32 x7C;
    /* 0x080 */ mh_f32 x80;
    /* 0x084 */ mh_f32 x84;
    /* 0x088 */ mh_f32 x88;
    /* 0x08C */ mh_f32 x8C;
    /* 0x090 */ mh_f32 x90;
    /* 0x094 */ mh_f32 x94;
    /* 0x098 */ mh_s16 ft_max_y;
    /* 0x09A */ mh_s16 x9E;
    /* 0x09C */ mh_f32 x9C;
    /* 0x0A0 */ mh_f32 xA0;
    /* 0x0A4 */ mh_s16 xA4;
    /* 0x0A6 */ mh_s16 xA6;
    /* 0x0A8 */ mh_s16 xA8;
    /* 0x0AC */ void* field_ixs;
    /* 0x0B0 */ void* xB0;
    /* 0x0B4 */ void* xB4;
    /* 0x0B8 */ mh_s16 xB8;
    /* 0x0BA */ mh_s16 pad;
    /* 0x0BC */ mh_u16 xBC_0_kind;
    /* 0x0BE */ mh_u8 xBC_0_x2;
    /* 0x0BF */ mh_u8 xBC_0_respawn;
    /* 0x0C0 */ mh_u16 xBC_1_kind;
    /* 0x0C2 */ mh_u8 xBC_1_x2;
    /* 0x0C3 */ mh_u8 xBC_1_respawn;
    /* 0x0C4 */ mh_u16 xBC_2_kind;
    /* 0x0C6 */ mh_u8 xBC_2_x2;
    /* 0x0C7 */ mh_u8 xBC_2_respawn;
    /* 0x0C8 */ mh_u16 xBC_3_kind;
    /* 0x0CA */ mh_u8 xBC_3_x2;
    /* 0x0CB */ mh_u8 xBC_3_respawn;
    /* 0x0CC */ mh_u16 xBC_4_kind;
    /* 0x0CE */ mh_u8 xBC_4_x2;
    /* 0x0CF */ mh_u8 xBC_4_respawn;
    /* 0x0D0 */ mh_u16 xBC_5_kind;
    /* 0x0D2 */ mh_u8 xBC_5_x2;
    /* 0x0D3 */ mh_u8 xBC_5_respawn;
    /* 0x0D4 */ mh_u16 xBC_6_kind;
    /* 0x0D6 */ mh_u8 xBC_6_x2;
    /* 0x0D7 */ mh_u8 xBC_6_respawn;
    /* 0x0D8 */ mh_u16 xBC_7_kind;
    /* 0x0DA */ mh_u8 xBC_7_x2;
    /* 0x0DB */ mh_u8 xBC_7_respawn;
    /* 0x0DC */ mh_u16 xBC_8_kind;
    /* 0x0DE */ mh_u8 xBC_8_x2;
    /* 0x0DF */ mh_u8 xBC_8_respawn;
    /* 0x0E0 */ mh_u16 xBC_9_kind;
    /* 0x0E2 */ mh_u8 xBC_9_x2;
    /* 0x0E3 */ mh_u8 xBC_9_respawn;
    /* 0x0E4 */ mh_u16 xBC_10_kind;
    /* 0x0E6 */ mh_u8 xBC_10_x2;
    /* 0x0E7 */ mh_u8 xBC_10_respawn;
    /* 0x0E8 */ mh_u16 xBC_11_kind;
    /* 0x0EA */ mh_u8 xBC_11_x2;
    /* 0x0EB */ mh_u8 xBC_11_respawn;
    /* 0x0EC */ mh_u16 xBC_12_kind;
    /* 0x0EE */ mh_u8 xBC_12_x2;
    /* 0x0EF */ mh_u8 xBC_12_respawn;
    /* 0x0F0 */ mh_u16 xBC_13_kind;
    /* 0x0F2 */ mh_u8 xBC_13_x2;
    /* 0x0F3 */ mh_u8 xBC_13_respawn;
    /* 0x0F4 */ mh_u16 xBC_14_kind;
    /* 0x0F6 */ mh_u8 xBC_14_x2;
    /* 0x0F7 */ mh_u8 xBC_14_respawn;
    /* 0x0F8 */ mh_u16 xBC_15_kind;
    /* 0x0FA */ mh_u8 xBC_15_x2;
    /* 0x0FB */ mh_u8 xBC_15_respawn;
    /* 0x0FC */ mh_u16 xBC_16_kind;
    /* 0x0FE */ mh_u8 xBC_16_x2;
    /* 0x0FF */ mh_u8 xBC_16_respawn;
    /* 0x100 */ mh_u16 xBC_17_kind;
    /* 0x102 */ mh_u8 xBC_17_x2;
    /* 0x103 */ mh_u8 xBC_17_respawn;
    /* 0x104 */ mh_u16 xBC_18_kind;
    /* 0x106 */ mh_u8 xBC_18_x2;
    /* 0x107 */ mh_u8 xBC_18_respawn;
    /* 0x108 */ mh_u16 xBC_19_kind;
    /* 0x10A */ mh_u8 xBC_19_x2;
    /* 0x10B */ mh_u8 xBC_19_respawn;
    /* 0x10C */ mh_u16 xBC_20_kind;
    /* 0x10E */ mh_u8 xBC_20_x2;
    /* 0x10F */ mh_u8 xBC_20_respawn;
    /* 0x110 */ mh_u16 xBC_21_kind;
    /* 0x112 */ mh_u8 xBC_21_x2;
    /* 0x113 */ mh_u8 xBC_21_respawn;
    /* 0x114 */ mh_u16 xBC_22_kind;
    /* 0x116 */ mh_u8 xBC_22_x2;
    /* 0x117 */ mh_u8 xBC_22_respawn;
    /* 0x118 */ mh_u16 xBC_23_kind;
    /* 0x11A */ mh_u8 xBC_23_x2;
    /* 0x11B */ mh_u8 xBC_23_respawn;
    /* 0x11C */ mh_u16 xBC_24_kind;
    /* 0x11E */ mh_u8 xBC_24_x2;
    /* 0x11F */ mh_u8 xBC_24_respawn;
    /* 0x120 */ mh_u16 xBC_25_kind;
    /* 0x122 */ mh_u8 xBC_25_x2;
    /* 0x123 */ mh_u8 xBC_25_respawn;
    /* 0x124 */ mh_u16 xBC_26_kind;
    /* 0x126 */ mh_u8 xBC_26_x2;
    /* 0x127 */ mh_u8 xBC_26_respawn;
    /* 0x128 */ mh_u16 xBC_27_kind;
    /* 0x12A */ mh_u8 xBC_27_x2;
    /* 0x12B */ mh_u8 xBC_27_respawn;
    /* 0x12C */ mh_u16 xBC_28_kind;
    /* 0x12E */ mh_u8 xBC_28_x2;
    /* 0x12F */ mh_u8 xBC_28_respawn;
    /* 0x130 */ mh_u16 xBC_29_kind;
    /* 0x132 */ mh_u8 xBC_29_x2;
    /* 0x133 */ mh_u8 xBC_29_respawn;
    /* 0x134 */ mh_u16 xBC_30_kind;
    /* 0x136 */ mh_u8 xBC_30_x2;
    /* 0x137 */ mh_u8 xBC_30_respawn;
    /* 0x138 */ mh_u16 xBC_31_kind;
    /* 0x13A */ mh_u8 xBC_31_x2;
    /* 0x13B */ mh_u8 xBC_31_respawn;
};

/* grinishie1.c: struct grInishie1_YakumonoParam */
struct melee_host_yakumono_inishie1 {
    /* 0x000 */ mh_f32 unk0;
    /* 0x004 */ mh_f32 unk4;
    /* 0x008 */ mh_f32 unk8;
    /* 0x00C */ mh_f32 unkC;
    /* 0x010 */ mh_f32 unk10;
    /* 0x014 */ mh_s16 unk14;
    /* 0x016 */ mh_s16 unk16;
    /* 0x018 */ mh_u16 unk18;
    /* 0x01A */ mh_s16 unk1A;
    /* 0x01C */ mh_s16 unk1C;
    /* 0x01E */ mh_s16 unk1E;
    /* 0x020 */ mh_f32 unk20;
    /* 0x024 */ mh_f32 unk24;
    /* 0x028 */ mh_f32 unk28;
    /* 0x02C */ mh_f32 unk2C_0_x;
    /* 0x030 */ mh_f32 unk2C_0_y;
    /* 0x034 */ mh_f32 unk2C_0_z;
    /* 0x038 */ mh_f32 unk2C_1_x;
    /* 0x03C */ mh_f32 unk2C_1_y;
    /* 0x040 */ mh_f32 unk2C_1_z;
    /* 0x044 */ mh_f32 unk44;
    /* 0x048 */ mh_f32 unk48;
    /* 0x04C */ mh_f32 unk4C;
    /* 0x050 */ mh_f32 unk50;
};

/* grinishie2.c: struct grInishie2_YakumonoParam */
struct melee_host_yakumono_inishie2 {
    /* 0x000 */ mh_s16 unk0;
    /* 0x002 */ mh_s16 unk2;
    /* 0x004 */ mh_s16 unk4;
    /* 0x006 */ mh_s16 unk6;
    /* 0x008 */ mh_s16 unk8;
    /* 0x00A */ mh_s16 unkA;
    /* 0x00C */ mh_s16 unkC;
    /* 0x00E */ mh_s16 unkE;
    /* 0x010 */ mh_s16 unk10[2];
    /* 0x014 */ mh_f32 unk14_0_x;
    /* 0x018 */ mh_f32 unk14_0_y;
    /* 0x01C */ mh_f32 unk14_0_z;
    /* 0x020 */ mh_f32 unk14_1_x;
    /* 0x024 */ mh_f32 unk14_1_y;
    /* 0x028 */ mh_f32 unk14_1_z;
    /* 0x02C */ mh_f32 unk2C;
    /* 0x030 */ mh_f32 unk30_0_x;
    /* 0x034 */ mh_f32 unk30_0_y;
    /* 0x038 */ mh_f32 unk30_0_z;
    /* 0x03C */ mh_f32 unk30_1_x;
    /* 0x040 */ mh_f32 unk30_1_y;
    /* 0x044 */ mh_f32 unk30_1_z;
    /* 0x048 */ mh_s16 unk48;
    /* 0x04A */ mh_s16 unk4A;
};

/* grflatzone.c: struct grFlatzone_YakumonoParam */
struct melee_host_yakumono_flatzone {
    /* 0x000 */ mh_s32 unk0;
    /* 0x004 */ mh_s32 unk4;
    /* 0x008 */ mh_s32 unk8;
    /* 0x00C */ mh_s32 unkC;
    /* 0x010 */ mh_s32 unk10;
    /* 0x014 */ mh_s32 unk14;
    /* 0x018 */ mh_s32 unk18;
    /* 0x01C */ mh_s32 unk1C;
    /* 0x020 */ mh_s32 unk20;
    /* 0x024 */ mh_f32 unk24;
    /* 0x028 */ mh_f32 unk28;
    /* 0x02C */ mh_s32 unk2C;
    /* 0x030 */ mh_s32 unk30;
    /* 0x034 */ mh_s32 unk34;
    /* 0x038 */ mh_f32 unk38;
    /* 0x03C */ mh_s32 unk3C;
};

/* groldpupupu.c: struct grOldpupupu_YakumonoParam */
struct melee_host_yakumono_oldpupupu {
    /* 0x000 */ mh_s16 x0;
    /* 0x002 */ mh_s16 x2;
    /* 0x004 */ mh_s16 x4;
    /* 0x006 */ mh_s16 x6;
    /* 0x008 */ mh_s32 x8;
    /* 0x00C */ mh_s32 xC;
    /* 0x010 */ mh_f32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_f32 x24;
    /* 0x028 */ mh_f32 x28;
    /* 0x02C */ mh_f32 x2C;
    /* 0x030 */ mh_f32 x30;
};

/* groldyoshi.c: anon */
struct melee_host_yakumono_oldyoshi {
    /* 0x000 */ mh_s16 x0;
    /* 0x002 */ mh_s16 x2;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_f32 x8;
    /* 0x00C */ mh_f32 xC;
    /* 0x010 */ mh_s16 x10;
    /* 0x012 */ mh_s16 x12;
    /* 0x014 */ mh_s16 x14;
    /* 0x016 */ mh_s16 x16;
    /* 0x018 */ mh_s16 x18;
};

/* groldkongo.c: struct grOldKongo_YakumonoParam */
struct melee_host_yakumono_oldkongo {
    /* 0x000 */ mh_s16 rframe_bird_wait_a;
    /* 0x002 */ mh_s16 rframe_bird_wait_b;
    /* 0x004 */ mh_f32 rrange_bird_random_offset_y;
    /* 0x008 */ mh_f32 rframe_barrel_shoot_a;
    /* 0x00C */ mh_f32 rframe_barrel_shoot_b;
    /* 0x010 */ mh_f32 rframe_barrel_in;
    /* 0x014 */ mh_f32 rframe_barrel_wait_a;
    /* 0x018 */ mh_f32 rframe_barrel_wait_b;
    /* 0x01C */ mh_f32 rspeed_barrel_rot_accel;
    /* 0x020 */ mh_f32 rspeed_barrel_rot_max;
    /* 0x024 */ mh_f32 rframe_barrel_roll_a;
    /* 0x028 */ mh_f32 rframe_barrel_roll_b;
    /* 0x02C */ mh_s16 rrate_barrel_ld;
    /* 0x02E */ mh_s16 rrate_barrel_l;
    /* 0x030 */ mh_s16 rrate_barrel_lu;
    /* 0x032 */ mh_s16 rrate_barrel_u;
    /* 0x034 */ mh_s16 rrate_barrel_ru;
    /* 0x036 */ mh_s16 rrate_barrel_r;
    /* 0x038 */ mh_s16 rrate_barrel_rd;
    /* 0x03A */ mh_s16 rrate_barrel_d;
    /* 0x03C */ mh_s32 rframe_barrel_interval_a;
    /* 0x040 */ mh_s32 rframe_barrel_interval_b;
    /* 0x044 */ mh_f32 rspeed_barrel_move_accel;
    /* 0x048 */ mh_f32 rspeed_barrel_move_max;
    /* 0x04C */ mh_s32 rframe_barrel_stop_a;
    /* 0x050 */ mh_s32 rframe_barrel_stop_b;
    /* 0x054 */ mh_s32 rpower_barrel_attack;
    /* 0x058 */ mh_s32 rvector_barrel_attack;
    /* 0x05C */ mh_s32 rreff_barrel_attack;
    /* 0x060 */ mh_s32 rrfix_barrel_attack;
    /* 0x064 */ mh_s32 rradd_barrel_attack;
    /* 0x068 */ mh_s32 x68;
    /* 0x06C */ void* x6C;
};

/* grkinokoroute.c: anon */
struct melee_host_yakumono_kinokoroute {
    /* 0x000 */ mh_s32 x0;
    /* 0x004 */ mh_u16 x4_kind;
    /* 0x006 */ mh_u8 x4_x2;
    /* 0x007 */ mh_u8 x4_respawn;
};

/* grshrineroute.c: struct grShrineRoute_YakumonoParam */
struct melee_host_yakumono_shrineroute {
    /* 0x000 */ void* x0;
    /* 0x004 */ void* x4;
    /* 0x008 */ void* x8;
    /* 0x00C */ void* xC;
    /* 0x010 */ mh_s32 x10;
    /* 0x014 */ mh_f32 x14;
    /* 0x018 */ mh_f32 x18;
    /* 0x01C */ mh_f32 x1C;
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_s32 x24;
    /* 0x028 */ mh_u16 spawn_desc_kind;
    /* 0x02A */ mh_u8 spawn_desc_x2;
    /* 0x02B */ mh_u8 spawn_desc_respawn;
};

/* grzebesroute.c: struct grZebesRoute_YakumonoParam */
struct melee_host_yakumono_zebesroute {
    /* 0x000 */ mh_s32 camera_timer;
    /* 0x004 */ mh_s32 zako_spawn_chance;
};

/* grbigblueroute.c: struct grBigBlueRoute_YakumonoParam */
struct melee_host_yakumono_bigblueroute {
    /* 0x000 */ mh_s32 x0;
    /* 0x004 */ mh_f32 x4;
    /* 0x008 */ mh_u8 pad_8[24];
    /* 0x020 */ mh_f32 x20;
    /* 0x024 */ mh_u8 pad_24[24];
    /* 0x03C */ mh_f32 x3C;
    /* 0x040 */ mh_f32 x40;
    /* 0x044 */ mh_f32 x44;
    /* 0x048 */ mh_f32 x48;
    /* 0x04C */ mh_f32 x4C;
};

/* grbattle.c: struct grBattle_YakumonoParam */
struct melee_host_yakumono_battle {
    /* 0x000 */ void* bg_curr_color_overlay;
    /* 0x004 */ void* bg_prev_color_overlay;
};

/* grlast.c: anon */
struct melee_host_yakumono_last {
    /* 0x000 */ void* x0;
    /* 0x004 */ void* x4;
    /* 0x008 */ void* x8;
    /* 0x00C */ void* xC;
};

#endif
