#!/usr/bin/env python3
"""Generate the native playable-stage allowlist from the measured status."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

PORT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = PORT / "data/stage_status.json"
OUTPUT = PORT / "src/game/playable_stages.c.inc"


def generate() -> str:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1:
        raise ValueError("unsupported stage-status schema")
    stages = document.get("stages")
    if not isinstance(stages, list) or len(stages) != 30:
        raise ValueError("stage status must contain the 30 select-screen entries")
    kinds: set[int] = set()
    playable: list[tuple[int, str]] = []
    for stage in stages:
        kind = stage.get("kind")
        name = stage.get("name")
        enabled = stage.get("playable")
        if (not isinstance(kind, int) or not isinstance(name, str) or
                not isinstance(enabled, bool) or kind in kinds):
            raise ValueError(f"invalid or duplicate stage entry: {stage!r}")
        kinds.add(kind)
        if stage.get("random", False) and enabled:
            raise ValueError("the random square is not a stage to enable")
        if enabled:
            playable.append((kind, name))
    playable.sort()
    lines = [
        "/* Generated by port/tools/gen_stage_status.py from",
        " * port/data/stage_status.json. Do not edit by hand. */",
        "static const mh_u8 melee_host_playable_stkinds[] = {",
    ]
    lines.extend(f"    {kind}, /* {name} */" for kind, name in playable)
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generated = generate()
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"cannot generate stage status: {error}", file=sys.stderr)
        return 2
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"{OUTPUT.relative_to(PORT.parent)} is stale; rerun {__file__}",
                  file=sys.stderr)
            return 1
        print("playable-stage status is up to date")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(PORT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
